# Generated by Django 4.2.2 on 2023-07-15 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("purchase_time", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("stop_number", models.IntegerField()),
                ("stop_name", models.CharField(max_length=100)),
                ("arrival_time", models.CharField(max_length=100)),
                ("stop_duration", models.CharField(max_length=100)),
                ("departure_time", models.CharField(max_length=100)),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rjd_app.train"
                    ),
                ),
            ],
        ),
    ]
